on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up JDK 17 ☕
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Set up Display 📺
      run: |
        sudo apt-get install mutter dbus-x11;
        dbus-launch --auto-syntax > dbus-env;
        source dbus-env;
        mutter --no-x11 --headless --virtual-monitor 1920x1080 &
    - name: Build with Maven 🏗️
      run: mvn -B clean verify -pl !jdt-ls-fork/org.eclipse.jdt.ls.tests,!jdt-ls-fork/org.eclipse.jdt.ls.tests.syntaxserver
